export const dummyUserNotes = [
  {
    _id: "1",
    contentId: "content-1",
    title: "Introduction to React",
    content: "# React Basics\n\n- Component-based architecture\n- JSX syntax\n- Virtual DOM",
    userId: "user-abc",
    skillId: "skill-react",
    moduleId: "module-frontend",
    submoduleId: "submodule-react-intro",
    skillName: "React Development",
    moduleName: "Frontend Fundamentals",
    submoduleName: "Introduction",
    createdAt: "2025-01-12T10:30:00Z",
  },
  {
    _id: "2",
    contentId: "content-2",
    title: "State Management",
    content: "## useState & useReducer\n\n- `useState` for local state\n- `useReducer` for complex state logic",
    userId: "user-abc",
    skillId: "skill-react",
    moduleId: "module-frontend",
    submoduleId: "submodule-state",
    skillName: "React Development",
    moduleName: "Frontend Fundamentals",
    submoduleName: "State Management",
    createdAt: "2025-02-03T14:15:00Z",
  },
  {
    _id: "3",
    contentId: "content-3",
    title: "Node.js Basics",
    content: "## Node.js\n\n- Event-driven, non-blocking I/O\n- Uses V8 engine\n- Package management with npm",
    userId: "user-abc",
    skillId: "skill-node",
    moduleId: "module-backend",
    submoduleId: "submodule-node-intro",
    skillName: "Node.js Development",
    moduleName: "Backend Fundamentals",
    submoduleName: "Introduction",
    createdAt: "2025-03-10T09:00:00Z",
  },
  {
    _id: "4",
    contentId: "content-4",
    title: "Express Routing",
    content: "## Express.js Routing\n\n- Define routes with `app.get`, `app.post`\n- Middleware support\n- Router modularization",
    userId: "user-abc",
    skillId: "skill-node",
    moduleId: "module-backend",
    submoduleId: "submodule-express-routing",
    skillName: "Node.js Development",
    moduleName: "Backend Fundamentals",
    submoduleName: "Routing",
    createdAt: "2025-04-05T18:45:00Z",
  },
  {
    _id: "5",
    contentId: "content-5",
    title: "MongoDB Basics",
    content: "## MongoDB\n\n- NoSQL database\n- Stores data in BSON format\n- Collections & Documents",
    userId: "user-abc",
    skillId: "skill-mongo",
    moduleId: "module-database",
    submoduleId: "submodule-mongo-intro",
    skillName: "MongoDB",
    moduleName: "Database Fundamentals",
    submoduleName: "Introduction",
    createdAt: "2025-05-20T12:10:00Z",
  },
  {
    _id: "6",
    contentId: "content-6",
    title: "Mongoose ODM",
    content: "## Mongoose\n\n- Schema-based modeling\n- Middleware (pre/post hooks)\n- Validation and population",
    userId: "user-abc",
    skillId: "skill-mongo",
    moduleId: "module-database",
    submoduleId: "submodule-mongoose",
    skillName: "MongoDB",
    moduleName: "Database Fundamentals",
    submoduleName: "Mongoose",
    createdAt: "2025-06-25T16:20:00Z",
  },
  {
    _id: "7",
    contentId: "content-7",
    title: "Git & GitHub",
    content: "## Git Basics\n\n- Version control\n- Branching & merging\n- Remote repositories",
    userId: "user-abc",
    skillId: "skill-git",
    moduleId: "module-tools",
    submoduleId: "submodule-git-intro",
    skillName: "Version Control",
    moduleName: "Developer Tools",
    submoduleName: "Git",
    createdAt: "2025-07-15T11:05:00Z",
  },
  {
    _id: "8",
    contentId: "content-8",
    title: "Docker Essentials",
    content: "I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.I now have a completely functioning MVP ready with me (if we ignore the notes creating and saving in db for a submodule). Currently, the app is focussed on providing facility for only the tech related skills. A friend of mine has advised me to not be confined to only tech skills, but expand it for anything the user wished to learn. He was of the opinion that choosing to stay tech specific would limit my target audience, and put me against well-established competitors.",
    userId: "user-abc",
    skillId: "skill-docker",
    moduleId: "module-devops",
    submoduleId: "submodule-docker",
    skillName: "DevOps",
    moduleName: "Deployment",
    submoduleName: "Docker",
    createdAt: "2025-08-10T08:40:00Z",
  },
];
